import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ClerkProvider } from "@clerk/nextjs";
import QueryClientProvi from "@/components/react-query";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "ATLAS",
  description: "Generated by create next app",
  icons : {
    icon : "/logo.png"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <QueryClientProvi>
    <html lang="en">
      <body>
        <Navbar/>
        <main className="pt-[70px]">
        {children}
        <Toaster position="top-right"/>
        </main>
      </body>
    </html>
    </QueryClientProvi>
    </ClerkProvider>
  );
}
